pants = ["none","shorts", "Sweatpants", "Ripped Jeans", "Cargo Pants", "Dress Slacks", "Tailored Trousers", "Yoga Leggings"]
Shirts = ["none", "T-Shirt", "Graphic T-Shirt", "Dress Shirt", "wife_beater"]
Outerwear = ["none","Leather Jacket", "Hoodie", "Trench Coat", "Blazer"]
Footwear_under = ["none","basic Socks", "long socks", "stockings"]
Footwear = ["none", "boots", "sneakers"]
underware_upper = ["none", "basic Bra"]
underware_lower =["none", "male Underware", "female Underware"]
Accessories_head = ["none", "Snapback", "Baseball Cap", "Beanie", "Bucket Hat", "Top Hat", "Fedora", "Newsboy Cap", "Balaclava", "Headband"]
Accessories_face = ["none", "Sunglasses", "Glasses" "Round Glasses"]
Accessories_face_mask = ["none", "Basic FaceMask"] # hides your idendety stopping reputation lost and gain
Accessories_back = ["none", "Backpack", "Gym Bag"] # bag items give more Inventory space
Accessories_neck = ["none ", "chocker"]
Accessories_hands = ["none ", "Cufflinks", "Watch"] # watch lets you see the in-game time
Dresses = ["none", "Sundress", "Evening Gown"]
coveralls = ["none", "Denim Overalls","Track Suit"]